### ISSUE TITLE
users: migrate users with no password

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio-migrator#39]
On Invenio 2.x, all people that logged in through ORCID an got an account [created for them](https://github.com/inveniosoftware/invenio-oauthclient/blob/v0.1.1/invenio_oauthclient/contrib/orcid.py#L187) had no password set (the value in SQL  for the password column is `NULL`).

When running user migration, [this line](https://github.com/inveniosoftware/invenio-migrator/blob/master/invenio_migrator/tasks/users.py#L62) fails as password is None.

What do you think is a good way to deal with this in Invenio 3? Shall we create a random password for them? Is leaving the password empty a possibility?

**Comment by jirikuncar** [comment]
IMHO Invenio-Accounts should allow an empty (`None`) password, but it should forbid user to login using empty password.

**Comment by jmartinm** [comment]
> IMHO Invenio-Accounts should allow an empty (None) password, but it should forbid user to login using empty password.

I think that was the behaviour in Invenio 2.x. I can have a look at what happens in the new `invenio-accounts` with empty password.

**Comment by jmartinm** [comment]
> I think that was the behaviour in Invenio 2.x. I can have a look at what happens in the new invenio-accounts with empty password.

Seems to be the same now. So I will just amend the `users` migration tasks to take that into account and put `None` in password.
